### ISSUE TITLE
Definir end-points del backend

### ISSUE THREAD

**Issue by AnotherOneByteTheDust** [fullstacktf/Narrativas-Backend#8]
**Fecha límite: 6/11/2020**
Definir end-points del backend

**Comment by AnotherOneByteTheDust** [comment]
### MVP

**/api/character/**

get /api/characters/$id
delete /api/characters/$id
patch /api/characters/$id 
post /api/character/

**/api/stories/**

get /api/stories/$id
delete /api/stories/$id
patch /api/stories/$id 
post /api/stories/

## Opcional

**/api/users/**

get /api/users/$id 
delete /api/users/$id
patch /api/users/$id
post /api/users/

**Comment by yodra** [comment]
Este tipo de cosas las pueden incluir en el README de backend.

**Comment by AdalDiazFarina** [comment]
okey luego las ponemos entonces
